export default class RouterName {
  public static readonly preAudit: string = '内容预审'
  public static readonly contentAudit: string = '内容审核'
  public static readonly devAccount: string = '开发者信息'
  public static readonly auditHistory: string = '审核历史'
  public static readonly keywordsManage: string = '关键词管理'
  public static readonly configManage: string = '配置项管理'
  public static readonly homeSwiperManage: string = '轮播图管理'
  public static readonly stickTalkManage: string = '置顶管理'
  public static readonly imgAuditHistory: string = '图片审核历史'
  public static readonly userIdentityAudit: string = '实名认证审核'
  public static readonly neutralWordManage: string = '中性词管理'

  public static readonly login: string = 'login'
  public static readonly layout: string = 'layout'
  public static readonly review: string = 'review'
  public static readonly adminUserAdd: string = 'adminUserAdd'
  public static readonly userImgIdentity: string = 'userImgIdentity'
  public static readonly userImgIdentityPage: string = 'userImgIdentity'
  public static readonly statistics: string = 'statistics'
  public static readonly keywordsManage1: string = '关键词管理1'
  public static readonly test: string = 'test'
}
