dependencies {
    implementation("com.socialuni.social:socialuni-common-api")
    implementation("com.socialuni.social:socialuni-common-sdk")
    implementation("com.socialuni.social:socialuni-im")
    implementation("com.socialuni.social:socialuni-im-sdk")
    implementation("com.socialuni.social:socialuni-web-sdk")
    implementation("com.socialuni.social:socialuni-user-sdk")
    implementation("com.socialuni.social:socialuni-community-sdk")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("jakarta.persistence:jakarta.persistence-api")
    implementation("cn.hutool:hutool-all")
    implementation("io.jsonwebtoken:jjwt")
    implementation("org.apache.commons:commons-lang3")
    developmentOnly("org.springframework.boot:spring-boot-devtools")
}