export default class SocialuniModuleName {
    static readonly socialOAuthModule = 'socialOAuth'
    static readonly socialCircleModule = 'socialCircle'
    static readonly socialAppModule = 'socialApp'
    static readonly socialTalkModule = 'socialTalk'
    static readonly socialUserModule = 'socialUser'
    static readonly socialConfigModule = 'socialConfig'
    static readonly socialSystemModule = 'socialSystem'
    static readonly socialChatModule = 'socialChat'
    static readonly socialPlatformModule = 'socialPlatform'
    static readonly socialNotifyModule = 'socialNotify'
    static readonly socialTagModule = 'socialTag'
    static readonly socialLocationModule = 'socialLocation'
    static readonly socialRouterModule = 'socialRouter'
}
