socialuni:
  socialuni-id: "d15502ebc20f4f21bf2b375f2b3ac312"
  secret-key: "d9a53b2892a540689b4ef608bdca3d2e"
#  central-server-url: "https://localpc.socialuni.cn:8091"
  app:
    static-resource-url: "https://cdxapp-1257733245.file.myqcloud.com"
    system-user-id: 1
  user:
    token-secret-key: "cf902df9f1c04f868d51ce8920f555bc"
  provider:
    qq:
      qq-mp-id: ""
      qq-mp-secret: ""
      qq-merchant-id: ""
      qq-merchant-key: ""
    wx:
      wx-app-id: ""
      wx-mp-id: ""
      wx-mp-secret: ""
      wx-merchant-id: ""
      wx-merchant-key: ""
  cloud:
    tencent:
      cos:
        secret-id: ""
        secret-key: ""
        region: ""
        bucket-name: ""
      sms:
        app-id: 1
        app-key: ""
        sms-sign: ""
        template-id: 1
  map:
    qq:
      secret-key: ""
server:
  port: 8093
  ssl:
    # 证书名称
    key-store: localpc.socialuni.cn.jks
    #密钥库密码
    key-store-password: fx6541k7gmz
    key-store-type: JKS
spring:
  datasource:
    url: jdbc:mysql://bj-cdb-3dq1yzws.sql.tencentcdb.com:60459/social_demo?characterEncoding=utf-8&useSSL=false
    username: social_demo996
    password: social_demo996
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      read-only: false
      #等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 600000
      #一个连接idle状态的最大时长（毫秒），超时则被释放
      idle-timeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放
      max-lifetime: 1800000
      login-timeout: 600
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((CPU内核数量 * 2) + 硬盘数量)
      maximum-pool-size: 600
      minimum-idle: 30
