config:
  systemId: 1
  tokenUrl:
  initAvatar:
  tokenKey:
  qq:
    mp:
      qq_mp_id:
      qq_mp_secret:
    merchant:
      qq_merchant_id:
      qq_merchant_key:
    cos:
      secretId: 1
      secretKey:
      region:
      bucketName:
      imgUrl:
    sms:
      appId: 1
      appKey:
      templateId: 1
      smsSign:
  wx:
    mp:
      wx_mp_id:
      wx_mp_secret:
    app:
      wx_app_id:
    merchant:
      wx_merchant_id:
      wx_merchant_key:
  tt:
    mp:
      tt_mp_id:
      tt_mp_secret:
  bd:
    mp:
      bd_mp_id:
      bd_mp_client_id:
      bd_mp_client_secret:
  ali:
    map:
      secretKey:
  wy:
    security:
      wy_security_id:
      wy_security_secret:
      wy_security_talk_business_id:
server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-8819v0ae.sql.tencentcdb.com:25014/qingchi_dev?characterEncoding=utf-8&useSSL=false
    username: qingchi_dev
    password: qingchi@dev11
    driver-class-name: com.mysql.jdbc.Driver
  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: "127.0.0.1"
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 500
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  cache:
    redis:
      time-to-live: 86400000
prop:
    upload-folder: img/
    linux-img-folder: "file:/Users/qinky/IdeaProjects/qingchi_base/img/"
    win-img-folder: "file:D:/workspace/qingchi_base/img/"
