spring:
  profiles:
    active: local
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

