spring:
  profiles:
    active: local
#    active: localprod
#    active: prod
  jpa:
    database: MYSQL
#    show-sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
logging:
#  level:
#    com.socialuni.social.sdk.mapper: DEBUG
  file: socialuni.log
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

