socialuni:
  provider:
    qq:
      qq-mp-id: ""
      qq-mp-secret: ""
      qq-merchant-id: ""
      qq-merchant-key: ""
    wx:
      wx-app-id: ""
      wx-mp-id: ""
      wx-mp-secret: ""
      wx-merchant-id: ""
      wx-merchant-key: ""
  cloud:
    tencent:
      cos:
        secret-id: ""
        secret-key: ""
        region: ""
        bucket-name: ""
      sms:
        app-id: 1
        app-key: ""
        sms-sign: ""
        template-id: 1
  map:
    ali:
      secret-key: ""
server:
  port: 8091
  ssl:
    # 证书名称
    key-store: localpc.qingchiapp.com.jks
    #密钥库密码
    key-store-password: 3bu32z78qm02
    key-store-type: JKS
spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-8819v0ae.sql.tencentcdb.com:25014/social_demo?characterEncoding=utf-8&useSSL=false
    username: social_demo996
    password: social_demo996
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      read-only: false
      #等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 600000
      #一个连接idle状态的最大时长（毫秒），超时则被释放
      idle-timeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放
      max-lifetime: 1800000
      login-timeout: 600
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((CPU内核数量 * 2) + 硬盘数量)
      maximum-pool-size: 200
      minimum-idle: 10
  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: "127.0.0.1"
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 30s
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 10
  cache:
    redis:
      time-to-live: 86400000
