spring:
  profiles:
#    active: local
#    active: localprod
#    active: prod
    active: dev
#    active: demo
#    active: qkylocal
  sql:
    init:
      mode: always
      data-locations: classpath:dataInit/data.sql
  jpa:
    database: MYSQL
    #    show-sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
  #不要为我们工程中的资源文件建立映射
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  web:
    resources:
      add-mappings: false
logging:
  file:
    name: admin.log