spring:
  profiles:
    active: local
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.qky.qingchi.chat: DEBUG
    com.qky.qingchi.talk: DEBUG
  file: qingchi.log

management:
  endpoints:
    web:
      exposure:
        include: 'loggers'