<template>
  <div class="h100p flex-col overflow-auto">
    <!--    头部行，查询条件和操作-->
    <div class="flex-none row-all-center pa">
      <div class="ml">
        <el-button type="primary" @click="queryKeyword(inputKeyword)">查询</el-button>
      </div>
    </div>

    <keywords-detail-table
      class="flex-1"
      :keywords="tempKeywords"
      :is-temp="true"
      @query="queryKeyword"
    />
  </div>
</template>

<script lang="ts">
import { Component, Vue , toNative} from 'vue-facing-decorator'
import KeywordsQueryAPI from '@/api/KeywordsQueryAPI'
import keywordsVO from '@/model/violateWord/KeywordsVO'
import keywordsTriggerVO from '@/model/violateWord/KeywordsTriggerVO'
import KeywordsManageAPI from '@/api/KeywordsManageAPI'
import keywordsTriggerDetailVO from '@/model/violateWord/KeywordsTriggerDetailVO'
import KeywordsDetailTable from '@/views/keywordManage/KeywordsDetailTable.vue'
import TriggerDetailTable from '@/views/keywordManage/TriggerDetailTable.vue'
// 违规率高不高
// 违规次数、文本次数、拼音次数

// 违规率、文本违规率、拼音违规率

// 不违规率、文本不违规率、拼音不违规率
// 违规率高不高
// 违规次数、文本次数、拼音次数

// 违规率、文本违规率、拼音违规率

// 不违规率、文本不违规率、拼音不违规率

@Component({
  components: { TriggerDetailTable, KeywordsDetailTable }
})
class ViolationHistoryPage extends Vue {
  tempKeywords: keywordsVO[] = []
  keywords: keywordsVO[] = []

  inputKeyword = ''

  triggers: keywordsTriggerVO[] = []

  // db的keywords
  tempKeyword: keywordsVO = null
  // 实时计算的keywords
  keyword: keywordsVO = null

  triggerDetails: keywordsTriggerDetailVO[] = []
  vioTriggerDetails: keywordsTriggerDetailVO[] = []

  matchType = '全部'

  // 查询 违规的历史，然后是否被关键词匹配，被关键词匹配了哪个，然后看正常的会不会被匹配
  // 然后根据违规的内容生成关键词
  //

  // 预，预审核，不更改用户状态。
  // 将动态设置为仅自己可见哪种状态

  created() {
    // this.queryKeyword()
  }

  get bottomTableDataList() {
    if (this.tempKeyword) {
      if (this.matchType === '文字') {
        return this.tempKeyword.triggers.filter(item => !item.usePinyin)
      } else if (this.matchType === '拼音') {
        return this.tempKeyword.triggers.filter(item => item.usePinyin)
      } else {
        return this.tempKeyword.triggers
      }
    }
    return []
  }

  queryKeyword() {
    const list = [
      '0部',
      '11厘米',
      '12厘米',
      '13厘米',
      '14厘米',
      '15厘米',
      '16厘米',
      '17厘米',
      '18厘米',
      '19厘米',
      '20厘米',
      '⑤',
      'AI换脸',
      'ASMR',
      'BABA',
      'GAN啥都行',
      'GHS',
      'HK',
      'HUKAN',
      'HU看',
      'H瞅',
      'J8',
      'LOOK',
      'LUO',
      'LUO聊',
      'M嘛',
      'M奴',
      'M玩',
      'PAO友',
      'P友',
      'SAO',
      'SE',
      'SESE',
      'SM',
      'SP',
      'S找',
      'TIAOJIAO',
      'TJ',
      'WENAI',
      'WU',
      'WW的',
      'W一',
      'W加',
      'W友',
      'W哥',
      'W啊',
      'W女',
      'W妹',
      'W妹妹',
      'W姐',
      'W对象',
      'W小',
      'W带你',
      'W点',
      'W的',
      'W的小',
      'W的小姐',
      'W的小姐姐',
      'XING',
      'ZW',
      '一个人在家',
      '一分钱',
      '一单一结',
      '一夜情',
      '一换一',
      '上个床',
      '上床',
      '下体照',
      '下载',
      '下面好难受',
      '下面照片',
      '下面难受',
      '不M',
      '不免',
      '不懂带你',
      '不正经',
      '不漏脸',
      '不白',
      '不穿衣服',
      '不花钱',
      '不贵',
      '丝袜',
      '两亿',
      '个M',
      '个炮',
      '中出',
      '为我花',
      '主人',
      '买片',
      '二维码',
      '互K',
      '互吗',
      '互康',
      '互慰',
      '互爽',
      '互的',
      '互看',
      '互瞅',
      '人妖',
      '什么都',
      '付费',
      '价格',
      '你懂',
      '便宜',
      '信用贷',
      '借我',
      '做爱',
      '偷情',
      '傻逼',
      '儿M',
      '免费',
      '养你',
      '养我',
      '兼职',
      '内裤',
      '凌辱',
      '几块',
      '出售',
      '出租',
      '分泌',
      '分泌物',
      '加我看',
      '包养',
      '十块',
      '卖片',
      '卖身',
      '卖逼',
      '反差',
      '发撒旦法的',
      '发泄',
      '发车',
      '受不了',
      '受虐',
      '变坏',
      '只文',
      '可K',
      '可K车',
      '可以互',
      '可以养你',
      '可以视',
      '可以色',
      '可文',
      '可看',
      '可约',
      '可验证',
      '吃亏',
      '同城约',
      '后半夜',
      '听话',
      '呜呜呜',
      '呜呜的',
      '呜的',
      '呼看',
      '命令',
      '咯聊',
      '哥哥巫',
      '哥哥玩的开',
      '哥哥让你',
      '哥哥需要',
      '哥哥需要看',
      '哥需要看',
      '啪啪',
      '喝牛奶',
      '喷水',
      '图在',
      '坏哥',
      '坏坏',
      '坏妹',
      '坏姐',
      '坏弟',
      '坏点',
      '处炮友',
      '夜晚',
      '夜聊',
      '夜需',
      '夜需要片',
      '夜需要片片',
      '大JB',
      '大冒险',
      '大叔上车',
      '大吊',
      '天性',
      '套套',
      '女M',
      '女主人',
      '女仆',
      '女儿',
      '女司机',
      '女同',
      '女奴',
      '奶头',
      '奶子',
      '好痒',
      '好色',
      '妈妈',
      '妈逼',
      '妹互',
      '妹妹身',
      '妹妹难受',
      '姐互',
      '姐妹互',
      '娇喘',
      '婊',
      '媳妇',
      '字母',
      '学习生物',
      '寂寞',
      '寂寞的小哥哥',
      '密小哥',
      '封了',
      '射爆',
      '射精',
      '小M',
      '小母',
      '小洞洞',
      '小火车',
      '小电影',
      '小色',
      '小额贷',
      '少FU',
      '少妇',
      '就干啥',
      '屋看',
      '屌丝',
      '巫女',
      '巫巫',
      '巫的',
      '巫的哥',
      '巫的哥哥',
      '巫老',
      '帮舔',
      '干啥都行',
      '干嘛都可',
      '干炮',
      '干逼',
      '幼女',
      '幼小',
      '床上',
      '开房',
      '开放',
      '开放的',
      '开视',
      '开车',
      '弄弟弟',
      '弄我',
      '强奸',
      '很S',
      '微偿',
      '急需用钱',
      '性女',
      '性欲',
      '惊喜',
      '想H',
      '想分享',
      '想变坏',
      '想日',
      '想曹',
      '想看',
      '想看的',
      '想给你',
      '想舒服',
      '想被',
      '想要看',
      '想要看我',
      '想赚',
      '想那个',
      '意想不到',
      '意淫',
      '慬的来',
      '懂别来',
      '懂加',
      '懂得',
      '懂我',
      '懂我意思',
      '懂男',
      '懂的',
      '懂粿',
      '我养你',
      '我头像',
      '我射',
      '我的下面',
      '才能进去',
      '扣B',
      '扮演',
      '找M',
      '找S',
      '找狗',
      '报酬',
      '拍片',
      '拼多多',
      '指挥',
      '挑逗',
      '捉弄',
      '换源',
      '换资源',
      '探讨',
      '探讨生理',
      '探讨身体',
      '插你',
      '搞钱',
      '摸着',
      '操吗',
      '操死',
      '操死我',
      '操逼',
      '收费',
      '放开',
      '放的开',
      '教我',
      '敢玩',
      '文AI',
      '文女',
      '文字',
      '文字交流',
      '文字游戏',
      '文学',
      '文学社',
      '文爱',
      '文的',
      '无下限',
      '有⃣️',
      '有M',
      '有QIAN',
      '有亏',
      '有互',
      '有偿',
      '有哥哥需要',
      '有哥哥需要看',
      '有母',
      '有片',
      '有钱',
      '有钱的',
      '服从',
      '服从命令',
      '期M',
      '来舒服',
      '棒大',
      '欣赏',
      '欲仙欲死',
      '母GOU',
      '母亲',
      '母狗',
      '母猴',
      '气喘吁吁',
      '氵亏',
      '没羞没臊',
      '泛滥',
      '洗澡',
      '流水',
      '深入',
      '深夜',
      '深夜放毒',
      '深夜需',
      '深夜需要',
      '深夜需要片片',
      '深浅',
      '深的',
      '湖看',
      '满足',
      '满足我',
      '潮牌鞋',
      '炮友',
      '点不一样',
      '点色',
      '点钱',
      '㸔覑',
      '父女',
      '父母',
      '父爱',
      '爸妈',
      '爸妈晚上',
      '爸爸',
      '片＋',
      '片片',
      '片片＋',
      '片片的',
      '片的',
      '牛奶',
      '物质',
      '玩伍',
      '玩嘛',
      '玩弄',
      '玩点不一样',
      '玩的开',
      '玩的开放的',
      '玩的起',
      '玩网',
      '玩随便',
      '生理',
      '生理知识',
      '用钱',
      '痒嘛',
      '痒死',
      '痛经',
      '百合',
      '的吊',
      '的开放',
      '的开放的',
      '直喷水',
      '直奔主题',
      '直插',
      '直播',
      '看➕',
      '看下面',
      '看吗',
      '看图',
      '看女',
      '看妹',
      '看妹妹',
      '看妹妹的',
      '看妹妹的加',
      '看妹妹那',
      '看妹身',
      '看小jj',
      '看小黄',
      '看屌',
      '看弄',
      '看懂',
      '看我的下面',
      '看深',
      '看片',
      '看片加',
      '看片的',
      '看看脚丫',
      '看私',
      '看胸',
      '看脚',
      '看腿',
      '看腿的',
      '看自拍',
      '看身',
      '看逼',
      '看那',
      '看那个',
      '看黄',
      '眯眯',
      '眼福',
      '破CHU',
      '破处',
      '磕炮',
      '视屏',
      '视爱',
      '视频',
      '福利',
      '私处',
      '私密',
      '秒射',
      '符合下面',
      '管教',
      '管理员',
      '精兵',
      '粿的',
      '红包',
      '约P',
      '约吗',
      '约炮',
      '约的',
      '约趴',
      '给KAN',
      '给上',
      '给你看',
      '给你钱',
      '给我看',
      '给看',
      '给钱',
      '缺钱',
      '网站',
      '网调',
      '羞羞',
      '羞辱',
      '老母',
      '聊S',
      '聊SAO',
      '聊内个',
      '聊坏',
      '聊湿',
      '聊那',
      '聊那种',
      '聊騷',
      '聊黄',
      '肉棒',
      '胯下舔',
      '胸大',
      '胸好',
      '能H',
      '能艹',
      '脚的',
      '脱光',
      '自w',
      '自卫',
      '自慰',
      '舒服',
      '舒服舒服',
      '舔В',
      '舔你',
      '舔到',
      '色丝袜',
      '色人',
      '色匹',
      '色哥',
      '色妹',
      '色姐',
      '色弟',
      '色比',
      '色狼',
      '色男',
      '色色',
      '艹你',
      '花钱',
      '虎看',
      '虐待',
      '被虐',
      '被调',
      '裸聊',
      '裸聊看',
      '要 开启',
      '要H',
      '要母',
      '要片片＋',
      '要看妹',
      '要看妹妹',
      '要看妹妹的',
      '要看妹妹的加',
      '要视',
      '要资源',
      '要那个',
      '要钱',
      '角色',
      '认为高概率的',
      '让你爽',
      '让你舒服',
      '让干啥',
      '让干啥就干啥',
      '让您舒服',
      '让我们',
      '让我舒服',
      '让操',
      '试看',
      '诚信',
      '说什么干什么',
      '调教',
      '调母',
      '购物车',
      '贱狗',
      '贴身',
      '费用',
      '费看',
      '资源',
      '资金',
      '赚点',
      '赚钱',
      '越SE',
      '跟妹妹',
      '身体',
      '身体构造',
      '身子',
      '车开',
      '软件',
      '进郡',
      '逼的',
      '那个的',
      '那种东西',
      '释放',
      '重口',
      '长短',
      '阴茎',
      '阿姨',
      '陪睡',
      '隐私部位',
      '零花',
      '零钱',
      '需要',
      '需要加',
      '需要片',
      '需要片片',
      '需要片片＋',
      '需要的',
      '需要看',
      '需要看妹',
      '露不',
      '露脸',
      '面对面',
      '频需要➕',
      '颜色的',
      '风梢',
      '馋你',
      '騷不麦',
      '骚',
      '高C',
      '高朝',
      '高潮',
      '鲍鱼',
      '鸡吧',
      '黄一点',
      '黑丝'
    ]

    this.tempKeyword = null
    this.keywords = []
    KeywordsQueryAPI.keywordsAddList(list, 10000).then(res => {
      this.tempKeywords = res.data
    })
  }

  queryKeywords() {
    KeywordsQueryAPI.queryKeywordsAPI().then(res => {
      this.keywords = res.data
    })
  }

  scanTalkKeywords() {
    KeywordsQueryAPI.scanTalkKeywordsAPI()
  }

  scanCommentKeywords() {
    KeywordsQueryAPI.scanCommentKeywordsAPI()
  }

  scanMessageKeywords() {
    KeywordsQueryAPI.scanMessageKeywordsAPI()
  }

  testKeywords() {
    KeywordsManageAPI.testKeywordsAPI()
  }
}
export default toNative(ViolationHistoryPage)
</script>

<style scoped>

</style>
